---
site_name: The Dark Khaki Book Of Curiosities
site_description: My personal digital garden
site_author: MikhailS
site_url: https://mikhailspirin.github.io/khaki-book/

nav:
  - Introduction: index.md
  - Coding:
    - Challenges:
        - Codewars: coding/challenge/codewars.md
        - Leetcode: coding/challenge/leetcode.md
    - Atom Shortcuts: coding/atom-shortcuts.md
    - Markdown: coding/markdown.md
    - Python: coding/python.md
    - Python Packages: coding/python-packages.md
    - Pip: coding/pip.md
  - Electronics:
    - Repair:
      - Tascam DP-003SD: electronics/repair/dp003sd.md
      - Alesis Microverb III: electronics/repair/microverb.md
      - Livid Minim: electronics/repair/lividminim.md
    - Eurorack:
      - AI Synthesis Quad VCA: electronics/eurorackmodules/quadvca.md
      - JakPlugg uTides: electronics/eurorackmodules/tides.md
      - Befaco Sampling Modulator: electronics/eurorackmodules/samplingmodulator.md
      - Clouds: electronics/eurorackmodules/clouds.md
      - Strymon AA1: electronics/eurorackmodules/strymonaa1.md
      - Doepfer A-111-2: electronics/eurorackmodules/doepfer-a111-2.md
  - Generative:
    - Algorithms: generative/algorithms.md
    - Inspiration: generative/inspiration.md
    - Flow Fields: generative/flowfields.md
    - Shaders: generative/shaders.md
  - Media:
    - Movies: media/movies.md
    - Music: media/music.md
    - Books: media/books.md
  - Music:
    - Drums Learning: music/drumslearning.md
    - My Music: music/mymusic.md



theme:
  name: material
  custom_dir: theme
  features:
    - navigation.footer
    # - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

  palette:
    primary: custom

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/MikhailSpirin

extra_css:
  - stylesheets/extra.css

repo_name: MikhailSpirin/khaki-book
repo_url: https://github.com/MikhailSpirin/khaki-book
