---
site_name: The Dark Khaki Book Of Curiosities
site_description: My personal digital garden
site_author: MikhailS
site_url: https://mikhailspirin.github.io/khaki-book/

nav:
  - Introduction: index.md
  - Coding:
    - Python: coding/python.md
    - Pip: coding/pip.md
  - Generative:
    - Shaders: generative/shaders.md



theme:
  name: material
  custom_dir: theme
  features:
    - navigation.footer
    # - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

  palette:
    primary: custom

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/MikhailSpirin

extra_css:
  - stylesheets/extra.css

repo_name: MikhailSpirin/khaki-book
repo_url: https://github.com/MikhailSpirin/khaki-book
